version: '3.8'
services:
  frontend:
    build: 
      context: ./
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules

  backend:
    build: 
      context: ./
      dockerfile: backend/Dockerfile
    environment:
      - CLASSIFIER_URL=http://classifier:8001
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  classifier:
    build: 
      context: ./
      dockerfile: classifier/Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./classifier:/usr/src/app
